template: true
valuesFilePath: ./values.yml

resources:
  - name: sam_app_repo
    type: GitRepo
    configuration:
      gitProvider: {{.Values.myRepo.gitProvider}}
      path: {{ .Values.myRepo.path }}
      branches: 
        include: main

  # - name: sam_app_filespec
  #   type: FileSpec
  #   configuration:
  #     sourceArtifactory: tktest_lambda_nodejs
  #     pattern: package.yml
  #     target: /mypackage

pipelines:
  - name: sam_nodejs
    steps: 
      - name: build
        type: bash
        configuration:
          inputResources:
            - name: sam_app_repo
            #- name: sam_app_filespec
        execution:
          onExecute:
            - git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
            - mkdir ~/.linuxbrew/bin
            - ln -s ../Homebrew/bin/brew ~/.linuxbrew/bin
            - eval $(~/.linuxbrew/bin/brew shellenv)
            - brew --version
            - brew tap aws/tap
            - brew install aws-sam-cli
            - sam --version
            - sam package --template-file template.yml --output-template-file package.yml--s3-bucket tk-test-lambda-sam


           