template: true
valuesFilePath: ./values.yml

resources:
  - name: sam_app_repo
    type: GitRepo
    configuration:
      gitProvider: {{.Values.myRepo.gitProvider}}
      path: {{ .Values.myRepo.path }}
      branches: 
        include: main

  # - name: sam_app_filespec
  #   type: FileSpec
  #   configuration:
  #     sourceArtifactory: tktest_lambda_nodejs
  #     pattern: package.yml
  #     target: /mypackage

pipelines:
  - name: sam_nodejs
    steps: 
      - name: build
        type: bash
        configuration:
          inputResources:
            - name: sam_app_repo
            #- name: sam_app_filespec
        execution:
          onExecute:
            - sudo apt install python3-pip
            - pip3 --version
            - git clone https://github.com/awslabs/aws-sam-cli.git && cd aws-sam-cli
            - sudo python3 setup.py install 
            - cd .. && sudo rm -rf aws-sam-cli
            - sam --version
            - sam package --template-file template.yml --output-template-file package.yml--s3-bucket tk-test-lambda-sam


           