template: true
valuesFilePath: ./values.yml

resources:
  - name: sam_app_repo
    type: GitRepo
    configuration:
      gitProvider: {{.Values.myRepo.gitProvider}}
      path: {{ .Values.myRepo.path }}
      branches: 
        include: main

  - name: sam_app_filespec
    type: FileSpec
    configuration:
      sourceArtifactory: tktest-lambda
      pattern: package.yml
      target: /mypackage

pipelines:
  - name: sam_nodejs
    steps: 
      - name: build
        type: bash
        configuration:
          inputResources:
            - name: sam_app_repo
            - name: sam_app_filespec
        execution:
          onExecute:
            - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
            - test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            - test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
            - echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
            - brew --version
            - brew tap aws/tap
            - brew install aws-sam-cli
            - sam --version
            - sam package --template-file template.yml --output-template-file package.yml--s3-bucket tk-test-lambda-sam


           